### ISSUE TITLE
Boot.fex too large, update_mbr fail

### ISSUE THREAD

**Issue by dtischler** [BPI-SINOVOIP/BPI-M64-bsp-4.4#2]
Hello @Dangku 

Thank you for your hard work and effort!

I have cloned this repository today, and attempted to run a build using the normal ./build.sh process, but have run into an error.  During the build process, the kernel builds successfully, but the "pack" steps are leading to an error that you can see below.  It appears from this log file that boot.fex is too large?  And as a result, update_mbr fails.  No image file is created at the end.  Are you able to duplicate this, or, identify what I should update?  Thanks!

David

david@david-VirtualBox:~/Desktop/BPI-M64-bsp-4.4$ ./build.sh
top dir 
NOTICE:
new build.sh default select BPI-M64-720P and pack all boards
supported boards:
BPI-M64-720P
BPI-M64-LCD7

BPI-M64-720P configured. Now run `make`
This tool support following building mode(s):
--------------------------------------------------------------------------------
	1. Build all, uboot and kernel and pack to download images.
	2. Build uboot only.
	3. Build kernel only.
	4. kernel configure.
	5. Pack the builds to target download image, this step must execute after u-boot,
	   kernel and rootfs build out
	6. update files for SD
	7. Clean all build.
--------------------------------------------------------------------------------
Please choose a mode(1-7): 1

 Now building...

make -C u-boot-sunxi sun50iw1p1_config CROSS_COMPILE=/home/david/Desktop/BPI-M64-bsp-4.4/allwinner-tools/gcc-linaro/bin/arm-linux-gnueabi- -j4
make[1]: Entering directory '/home/david/Desktop/BPI-M64-bsp-4.4/u-boot-sunxi'
Configuring for sun50iw1p1 - Board: sun50iw1p1, Options: SUN50IW1P1
make[1]: Leaving directory '/home/david/Desktop/BPI-M64-bsp-4.4/u-boot-sunxi'
make -C u-boot-sunxi all CROSS_COMPILE=/home/david/Desktop/BPI-M64-bsp-4.4/allwinner-tools/gcc-linaro/bin/arm-linux-gnueabi- -j4
make[1]: Entering directory '/home/david/Desktop/BPI-M64-bsp-4.4/u-boot-sunxi'
  GEN     include/autoconf.mk.dep
  GEN     include/autoconf.mk
  CHK     include/config/uboot.release
  CHK     include/generated/timestamp_autogenerated.h
  UPD     include/generated/timestamp_autogenerated.h
  CHK     include/generated/version_autogenerated.h
  CC      lib/asm-offsets.s
  CC      arch/arm/lib/asm-offsets.s
  GEN     include/generated/asm-offsets.h
  GEN     include/generated/generic-asm-offsets.h

......<trimmed to save space>......

cpio: /home/david/Desktop/BPI-M64-bsp-4.4/linux-sunxi/output/usr/src/linux-headers-4.4.89-BPI-M64-Kernel/arch/xtensa/include/uapi/asm/msgbuf.h not created: newer or same age version exists
cpio: /home/david/Desktop/BPI-M64-bsp-4.4/linux-sunxi/output/usr/src/linux-headers-4.4.89-BPI-M64-Kernel/arch/xtensa/include/uapi/asm/Kbuild not created: newer or same age version exists
cpio: /home/david/Desktop/BPI-M64-bsp-4.4/linux-sunxi/output/usr/src/linux-headers-4.4.89-BPI-M64-Kernel/arch/xtensa/include/uapi/asm/types.h not created: newer or same age version exists
cpio: /home/david/Desktop/BPI-M64-bsp-4.4/linux-sunxi/output/usr/src/linux-headers-4.4.89-BPI-M64-Kernel/arch/xtensa/include/uapi/asm/mman.h not created: newer or same age version exists
cpio: /home/david/Desktop/BPI-M64-bsp-4.4/linux-sunxi/output/usr/src/linux-headers-4.4.89-BPI-M64-Kernel/arch/xtensa/include/uapi/asm/auxvec.h not created: newer or same age version exists
cpio: /home/david/Desktop/BPI-M64-bsp-4.4/linux-sunxi/output/usr/src/linux-headers-4.4.89-BPI-M64-Kernel/arch/xtensa/include/uapi/asm/termbits.h not created: newer or same age version exists
cpio: /home/david/Desktop/BPI-M64-bsp-4.4/linux-sunxi/output/usr/src/linux-headers-4.4.89-BPI-M64-Kernel/arch/xtensa/include/uapi/asm/socket.h not created: newer or same age version exists
cpio: /home/david/Desktop/BPI-M64-bsp-4.4/linux-sunxi/output/usr/src/linux-headers-4.4.89-BPI-M64-Kernel/arch/xtensa/include/uapi/asm/ptrace.h not created: newer or same age version exists
cpio: /home/david/Desktop/BPI-M64-bsp-4.4/linux-sunxi/output/usr/src/linux-headers-4.4.89-BPI-M64-Kernel/arch/xtensa/include/uapi/asm/sembuf.h not created: newer or same age version exists
cpio: /home/david/Desktop/BPI-M64-bsp-4.4/linux-sunxi/output/usr/src/linux-headers-4.4.89-BPI-M64-Kernel/arch/xtensa/include/uapi/asm/shmbuf.h not created: newer or same age version exists
0 blocks
Done - installed Kernel headers to /home/david/Desktop/BPI-M64-bsp-4.4/linux-sunxi/output
scripts/mk_pack.sh
BPIMACH=tulip-m64 tulip-noma
TARGET_PRODUCT=tulip-m64
MACH=sun50iw1p1, PLATFORM=tina, TARGET_PRODUCT=tulip-m64 BOARD=BPI-M64-720P
BPI: scripts/pack_img.sh -c sun50iw1p1 -p tina -b tulip-m64 -d uart0 -s none -m normal -v none -t /home/david/Desktop/BPI-M64-bsp-4.4
BPI: BOARD=BPI-M64-720P
No kernel param, parse it from tulip
copying tools file
copying configs file
storage_type value is -1
image/aultls32.fex
image/aultools.fex
image/boot_package.cfg
image/boot_package.fex
image/boot_package_nor.cfg
image/cardscript.fex
image/cardscript_secure.fex
image/cardtool.fex
image/env-3.10.cfg
image/env-3.4.cfg
image/env_burn.cfg
image/env.cfg
image/image.cfg
image/image_linux.cfg
image/split_xxxx.fex
image/sunxi.fex
image/sys_config.fex
image/sys_partition_dragonboard.fex
image/sys_partition_dump.fex
image/sys_partition.fex
image/sys_partition_private.fex
image/test_config.fex
image/toc0.fex
image/toc1.fex
image/usbtool.fex
image/usbtool_test.fex
/home/david/Desktop/BPI-M64-bsp-4.4
copying boot resource

LZMA 4.65 : Igor Pavlov : Public domain : 2009-02-03
copying boot file
make user resource for : /home/david/Desktop/BPI-M64-bsp-4.4/out/tulip-m64/image/sys_partition.fex
handle partition user-res
no user resource partitions
sys_config exist
Multiconfig num:0
copying tools file
copying configs file
storage_type value is -1
image/aultls32.fex
image/aultools.fex
image/boot0_nand.fex
image/boot0_sdcard.fex
image/boot0_spinor.fex
image/boot_package.cfg
image/boot_package.fex
image/boot_package_nor.cfg
image/cardscript.fex
image/cardscript_secure.fex
image/cardtool.fex
image/env-3.10.cfg
image/env-3.4.cfg
image/env_burn.cfg
image/env.cfg
image/fes1.fex
image/image.cfg
image/image_linux.cfg
image/monitor.fex
image/scp.fex
image/split_xxxx.fex
image/sunxi.fex
image/sys_config.fex
image/sys_partition_dragonboard.fex
image/sys_partition_dump.fex
image/sys_partition.fex
image/sys_partition_private.fex
image/test_config.fex
image/toc0.fex
image/toc1.fex
image/u-boot.fex
image/u-boot-spinor.fex
image/usbtool.fex
image/usbtool_test.fex
/home/david/Desktop/BPI-M64-bsp-4.4
copying boot resource

LZMA 4.65 : Igor Pavlov : Public domain : 2009-02-03
copying boot file
make user resource for : /home/david/Desktop/BPI-M64-bsp-4.4/out/tulip-m64/image/sys_partition.fex
handle partition user-res
no user resource partitions
p=soc c=product state=0
p=soc c=platform state=0
p=soc c=target state=0
p=soc c=power_sply state=0
p=soc c=card_boot state=0
p=soc c=pm_para state=0
p=soc c=card0_boot_para state=0
p=soc c=card2_boot_para state=0
p=soc c=twi_para state=0
p=soc c=uart_para state=0
p=soc c=jtag_para state=0
p=soc c=led_para state=0
p=soc c=clock state=0
p=soc c=dram state=0
p=soc c=gmac0 state=0
p=soc c=twi0 state=0
p=soc c=twi1 state=0
p=soc c=twi2 state=0
p=soc c=uart0 state=0
p=soc c=uart1 state=0
p=soc c=uart2 state=0
p=soc c=uart3 state=0
p=soc c=uart4 state=0
p=soc c=spi0 state=0
p=soc c=spi1 state=0
p=soc c=rtp_para state=0
p=soc c=ctp state=0
p=soc c=ctp_list state=0
p=soc c=tkey_para state=0
p=soc c=motor_para state=0
p=soc c=nand0 state=0
p=soc c=disp state=0
p=soc c=lcd0 state=0
p=soc c=backlight state=0
p=soc c=hdmi state=0
p=soc c=pwm0 state=0
p=soc c=pwm0 state=1
p=soc c=spwm0 state=0
p=soc c=spwm0 state=1
p=soc c=boot_disp state=0
p=soc c=csi0 state=0
p=csi0 c=csi0_dev0 state=0
p=csi0 c=csi0_dev1 state=0
p=soc c=tvout_para state=0
p=soc c=tvin_para state=0
p=soc c=di state=0
p=soc c=sdc0 state=0
p=soc c=sdc1 state=0
p=soc c=sdc2 state=0
p=soc c=smc state=0
p=soc c=usbc0 state=0
p=soc c=usbc1 state=0
p=soc c=serial_feature state=0
p=soc c=gsensor state=0
p=soc c=gsensor_list state=0
p=soc c=wlan state=0
p=soc c=bt state=0
p=soc c=btlpm state=0
p=soc c=3g_para state=0
p=soc c=gyroscopesensor state=0
p=soc c=gy_list state=0
p=soc c=lightsensor state=0
p=soc c=ls_list state=0
p=soc c=compasssensor state=0
p=soc c=compass_list state=0
p=soc c=spdif state=0
p=soc c=sndspdif state=0
p=soc c=daudio2 state=0
p=soc c=sndhdmi state=0
p=soc c=snddaudio0 state=0
p=soc c=daudio0 state=0
p=soc c=snddaudio1 state=0
p=soc c=daudio1 state=0
p=soc c=sndcodec state=0
p=soc c=i2s state=0
p=soc c=codec state=0
p=soc c=s_cir0 state=0
p=soc c=gpio_para state=0
p=soc c=pmu0 state=0
p=soc c=charger0 state=0
p=soc c=powerkey0 state=0
p=soc c=regulator0 state=0
p=soc c=axp_gpio0 state=0
p=soc c=recovery_key state=0
p=soc c=fastboot_key state=0
p=soc c=key_detect_en state=0
p=soc c=dvfs_table state=0
p=soc c=s_uart0 state=0
p=soc c=s_rsb0 state=0
p=soc c=s_jtag0 state=0
p=soc c=Vdevice state=0
p=soc c=gpu state=0
p=soc c=secure state=0
Conver script to dts ok.
update scp
before boot package
pack boot package
GetPrivateProfileSection read to end
content_count=6

toc1 file Path=/home/david/Desktop/BPI-M64-bsp-4.4/out/tulip-m64/image/boot_package.fex
script file Path=/home/david/Desktop/BPI-M64-bsp-4.4/out/tulip-m64/image/sys_config.bin

cant get board_id_enable
script update toc1 ok
packing for tina linux
normal
.....33333.....
.....44444.....
mbr count = 4

partitation file Path=/home/david/Desktop/BPI-M64-bsp-4.4/out/tulip-m64/image/sys_partition.bin
mbr_name file Path=/home/david/Desktop/BPI-M64-bsp-4.4/out/tulip-m64/image/sunxi_mbr.fex
download_name file Path=/home/david/Desktop/BPI-M64-bsp-4.4/out/tulip-m64/image/dlinfo.fex

mbr size = 16384
mbr magic softw411
disk name=boot-res
filename = boot-resource.fex 
dl_file_size = 7286 sector
part_size = 32768 sector
disk name=env
filename = env.fex 
dl_file_size = 256 sector
part_size = 2048 sector
disk name=misc
disk name=private
disk name=boot
 unable to open file boot.fex
dl file boot.fex size too large
update_for_part_info -1
update mbr file fail
ERROR: update_mbr failed
Makefile:56: recipe for target 'pack' failed
make: *** [pack] Error 1

 Build success!

david@david-VirtualBox:~/Desktop/BPI-M64-bsp-4.4$

**Comment by BPI-SINOVOIP** [comment]
Hi @dtischler ,

Please type the following two commands and show me the result.
# ls -l out/tulip-m64/
# ls -l out/tulip-m64/image/

**Comment by dtischler** [comment]
Hello and thank you!

It seems that the .img files are not getting created as part of the build and pack scripts, as you can see from these results, the "tulip-m64" is empty except for the "images" folder, which does contain the symlinks (even though they point to non-existent files).

Here is the output:


............
cpio: /home/david/Desktop/BPI-M64-bsp-4.4/linux-sunxi/output/usr/src/linux-headers-4.4.89-BPI-M64-Kernel/arch/xtensa/include/uapi/asm/socket.h not created: newer or same age version exists
cpio: /home/david/Desktop/BPI-M64-bsp-4.4/linux-sunxi/output/usr/src/linux-headers-4.4.89-BPI-M64-Kernel/arch/xtensa/include/uapi/asm/ptrace.h not created: newer or same age version exists
cpio: /home/david/Desktop/BPI-M64-bsp-4.4/linux-sunxi/output/usr/src/linux-headers-4.4.89-BPI-M64-Kernel/arch/xtensa/include/uapi/asm/sembuf.h not created: newer or same age version exists
cpio: /home/david/Desktop/BPI-M64-bsp-4.4/linux-sunxi/output/usr/src/linux-headers-4.4.89-BPI-M64-Kernel/arch/xtensa/include/uapi/asm/shmbuf.h not created: newer or same age version exists
0 blocks
Done - installed Kernel headers to /home/david/Desktop/BPI-M64-bsp-4.4/linux-sunxi/output
scripts/mk_pack.sh
BPIMACH=tulip-m64 tulip-noma
TARGET_PRODUCT=tulip-m64
MACH=sun50iw1p1, PLATFORM=tina, TARGET_PRODUCT=tulip-m64 BOARD=BPI-M64-720P
BPI: scripts/pack_img.sh -c sun50iw1p1 -p tina -b tulip-m64 -d uart0 -s none -m normal -v none -t /home/david/Desktop/BPI-M64-bsp-4.4
BPI: BOARD=BPI-M64-720P
No kernel param, parse it from tulip
copying tools file
copying configs file
storage_type value is -1
image/aultls32.fex
image/aultools.fex
image/boot_package.cfg
image/boot_package.fex
image/boot_package_nor.cfg
image/cardscript.fex
image/cardscript_secure.fex
image/cardtool.fex
image/env-3.10.cfg
image/env-3.4.cfg
image/env_burn.cfg
image/env.cfg
image/image.cfg
image/image_linux.cfg
image/split_xxxx.fex
image/sunxi.fex
image/sys_config.fex
image/sys_partition_dragonboard.fex
image/sys_partition_dump.fex
image/sys_partition.fex
image/sys_partition_private.fex
image/test_config.fex
image/toc0.fex
image/toc1.fex
image/usbtool.fex
image/usbtool_test.fex
/home/david/Desktop/BPI-M64-bsp-4.4
copying boot resource

LZMA 4.65 : Igor Pavlov : Public domain : 2009-02-03
copying boot file
make user resource for : /home/david/Desktop/BPI-M64-bsp-4.4/out/tulip-m64/image/sys_partition.fex
handle partition user-res
no user resource partitions
sys_config exist
Multiconfig num:0
copying tools file
copying configs file
storage_type value is -1
image/aultls32.fex
image/aultools.fex
image/boot0_nand.fex
image/boot0_sdcard.fex
image/boot0_spinor.fex
image/boot_package.cfg
image/boot_package.fex
image/boot_package_nor.cfg
image/cardscript.fex
image/cardscript_secure.fex
image/cardtool.fex
image/env-3.10.cfg
image/env-3.4.cfg
image/env_burn.cfg
image/env.cfg
image/fes1.fex
image/image.cfg
image/image_linux.cfg
image/monitor.fex
image/scp.fex
image/split_xxxx.fex
image/sunxi.fex
image/sys_config.fex
image/sys_partition_dragonboard.fex
image/sys_partition_dump.fex
image/sys_partition.fex
image/sys_partition_private.fex
image/test_config.fex
image/toc0.fex
image/toc1.fex
image/u-boot.fex
image/u-boot-spinor.fex
image/usbtool.fex
image/usbtool_test.fex
/home/david/Desktop/BPI-M64-bsp-4.4
copying boot resource

LZMA 4.65 : Igor Pavlov : Public domain : 2009-02-03
copying boot file
make user resource for : /home/david/Desktop/BPI-M64-bsp-4.4/out/tulip-m64/image/sys_partition.fex
handle partition user-res
no user resource partitions
p=soc c=product state=0
p=soc c=platform state=0
p=soc c=target state=0
p=soc c=power_sply state=0
p=soc c=card_boot state=0
p=soc c=pm_para state=0
p=soc c=card0_boot_para state=0
p=soc c=card2_boot_para state=0
p=soc c=twi_para state=0
p=soc c=uart_para state=0
p=soc c=jtag_para state=0
p=soc c=led_para state=0
p=soc c=clock state=0
p=soc c=dram state=0
p=soc c=gmac0 state=0
p=soc c=twi0 state=0
p=soc c=twi1 state=0
p=soc c=twi2 state=0
p=soc c=uart0 state=0
p=soc c=uart1 state=0
p=soc c=uart2 state=0
p=soc c=uart3 state=0
p=soc c=uart4 state=0
p=soc c=spi0 state=0
p=soc c=spi1 state=0
p=soc c=rtp_para state=0
p=soc c=ctp state=0
p=soc c=ctp_list state=0
p=soc c=tkey_para state=0
p=soc c=motor_para state=0
p=soc c=nand0 state=0
p=soc c=disp state=0
p=soc c=lcd0 state=0
p=soc c=backlight state=0
p=soc c=hdmi state=0
p=soc c=pwm0 state=0
p=soc c=pwm0 state=1
p=soc c=spwm0 state=0
p=soc c=spwm0 state=1
p=soc c=boot_disp state=0
p=soc c=csi0 state=0
p=csi0 c=csi0_dev0 state=0
p=csi0 c=csi0_dev1 state=0
p=soc c=tvout_para state=0
p=soc c=tvin_para state=0
p=soc c=di state=0
p=soc c=sdc0 state=0
p=soc c=sdc1 state=0
p=soc c=sdc2 state=0
p=soc c=smc state=0
p=soc c=usbc0 state=0
p=soc c=usbc1 state=0
p=soc c=serial_feature state=0
p=soc c=gsensor state=0
p=soc c=gsensor_list state=0
p=soc c=wlan state=0
p=soc c=bt state=0
p=soc c=btlpm state=0
p=soc c=3g_para state=0
p=soc c=gyroscopesensor state=0
p=soc c=gy_list state=0
p=soc c=lightsensor state=0
p=soc c=ls_list state=0
p=soc c=compasssensor state=0
p=soc c=compass_list state=0
p=soc c=spdif state=0
p=soc c=sndspdif state=0
p=soc c=daudio2 state=0
p=soc c=sndhdmi state=0
p=soc c=snddaudio0 state=0
p=soc c=daudio0 state=0
p=soc c=snddaudio1 state=0
p=soc c=daudio1 state=0
p=soc c=sndcodec state=0
p=soc c=i2s state=0
p=soc c=codec state=0
p=soc c=s_cir0 state=0
p=soc c=gpio_para state=0
p=soc c=pmu0 state=0
p=soc c=charger0 state=0
p=soc c=powerkey0 state=0
p=soc c=regulator0 state=0
p=soc c=axp_gpio0 state=0
p=soc c=recovery_key state=0
p=soc c=fastboot_key state=0
p=soc c=key_detect_en state=0
p=soc c=dvfs_table state=0
p=soc c=s_uart0 state=0
p=soc c=s_rsb0 state=0
p=soc c=s_jtag0 state=0
p=soc c=Vdevice state=0
p=soc c=gpu state=0
p=soc c=secure state=0
Conver script to dts ok.
update scp
before boot package
pack boot package
GetPrivateProfileSection read to end
content_count=6

toc1 file Path=/home/david/Desktop/BPI-M64-bsp-4.4/out/tulip-m64/image/boot_package.fex
script file Path=/home/david/Desktop/BPI-M64-bsp-4.4/out/tulip-m64/image/sys_config.bin

cant get board_id_enable
script update toc1 ok
packing for tina linux
normal
.....33333.....
.....44444.....
mbr count = 4

partitation file Path=/home/david/Desktop/BPI-M64-bsp-4.4/out/tulip-m64/image/sys_partition.bin
mbr_name file Path=/home/david/Desktop/BPI-M64-bsp-4.4/out/tulip-m64/image/sunxi_mbr.fex
download_name file Path=/home/david/Desktop/BPI-M64-bsp-4.4/out/tulip-m64/image/dlinfo.fex

mbr size = 16384
mbr magic softw411
disk name=boot-res
filename = boot-resource.fex 
dl_file_size = 7286 sector
part_size = 32768 sector
disk name=env
filename = env.fex 
dl_file_size = 256 sector
part_size = 2048 sector
disk name=misc
disk name=private
disk name=boot
 unable to open file boot.fex
dl file boot.fex size too large
update_for_part_info -1
update mbr file fail
ERROR: update_mbr failed
Makefile:56: recipe for target 'pack' failed
make: *** [pack] Error 1

 Build success!

david@david-VirtualBox:~/Desktop/BPI-M64-bsp-4.4$ ls -l out/tulip-m64/
total 4
drwxrwxr-x 3 david david 4096 Sep 13 18:23 image
david@david-VirtualBox:~/Desktop/BPI-M64-bsp-4.4$ ls -l out/tulip-m64/image/
total 7904
-rwxrwxr-x 1 david david  150819 Sep 13 18:23 aultls32.fex
-rwxrwxr-x 1 david david  164987 Sep 13 18:23 aultools.fex
-rw-rw-r-- 1 david david    1024 Sep 13 18:23 board_config.bin
-rw-rw-r-- 1 david david       9 Sep 13 18:23 board_config.fex
-rw-rw-r-- 1 david david    1024 Sep 13 18:23 board.fex
-rwxrwxr-x 1 david david   32768 Sep 13 18:23 boot0_nand.fex
-rwxrwxr-x 1 david david   32768 Sep 13 18:23 boot0_sdcard.fex
-rw-rw-r-- 1 david david   24576 Sep 13 18:23 boot0_spinor.fex
lrwxrwxrwx 1 david david      58 Sep 13 18:23 boot.fex -> /home/david/Desktop/BPI-M64-bsp-4.4/out/tulip-m64/boot.img
-rw-rw-r-- 1 david david  131699 Sep 13 18:23 bootlogo.bmp.lzma
-rwxrwxr-x 1 david david     281 Sep 13 18:23 boot_package.cfg
-rwxrwxr-x 1 david david 1409024 Sep 13 18:23 boot_package.fex
-rwxrwxr-x 1 david david     233 Sep 13 18:23 boot_package_nor.cfg
drwxrwxr-x 2 david david    4096 Sep 13 18:23 boot-resource
-rw-rw-r-- 1 david david 3730432 Sep 13 18:23 boot-resource.fex
-rw-rw-r-- 1 david david     598 Sep 13 18:23 boot-resource.ini
-rwxrwxr-x 1 david david    1758 Sep 13 18:23 cardscript.fex
-rwxrwxr-x 1 david david    1758 Sep 13 18:23 cardscript_secure.fex
-rwxrwxr-x 1 david david   72704 Sep 13 18:23 cardtool.fex
-rw-rw-r-- 1 david david   47104 Sep 13 18:23 config.fex
-rwxrwxr-x 1 david david    2199 Sep 13 18:23 env-3.10.cfg
-rwxrwxr-x 1 david david    1997 Sep 13 18:23 env-3.4.cfg
-rw-rw-r-- 1 david david     110 Sep 13 18:23 env_burn.cfg
-rwxrwxr-x 1 david david    3918 Sep 13 18:23 env.cfg
-rwxr--r-- 1 david david  131072 Sep 13 18:23 env.fex
-rwxrwxr-x 1 david david   16960 Sep 13 18:23 fes1.fex
-rwxrwxr-x 1 david david    4909 Sep 13 18:23 image.cfg
-rwxrwxr-x 1 david david    4594 Sep 13 18:23 image_linux.cfg
-rwxrwxr-x 1 david david   49624 Sep 13 18:23 monitor.fex
-rw-rw-r-- 1 david david      24 Sep 13 18:23 recovery.fex
lrwxrwxrwx 1 david david      60 Sep 13 18:23 rootfs.fex -> /home/david/Desktop/BPI-M64-bsp-4.4/out/tulip-m64/rootfs.img
-rwxrwxr-x 1 david david  103868 Sep 13 18:23 scp.fex
-rwxrwxr-x 1 david david     512 Sep 13 18:23 split_xxxx.fex
-rw-rw-r-- 1 david david   76919 Sep 13 18:23 sunxi.dtb
-rwxrwxr-x 1 david david   81408 Sep 13 18:23 sunxi.fex
-rw-rw-r-- 1 david david   47104 Sep 13 18:23 sys_config.bin
-rwxrwxr-x 1 david david   66771 Sep 13 18:23 sys_config.fex
-rwxrwxr-x 1 david david   65127 Sep 13 18:23 sys_config_fix.fex
-rw-rw-r-- 1 david david    2048 Sep 13 18:23 sys_partition.bin
-rwxrwxr-x 1 david david    2815 Sep 13 18:23 sys_partition_dragonboard.fex
-rwxrwxr-x 1 david david    1833 Sep 13 18:23 sys_partition_dump.fex
-rwxrwxr-x 1 david david    3247 Sep 13 18:23 sys_partition.fex
-rwxrwxr-x 1 david david    1958 Sep 13 18:23 sys_partition_private.fex
-rwxrwxr-x 1 david david   10342 Sep 13 18:23 test_config.fex
-rwxrwxr-x 1 david david       8 Sep 13 18:23 toc0.fex
-rwxrwxr-x 1 david david       8 Sep 13 18:23 toc1.fex
-rwxrwxr-x 1 david david  983040 Sep 13 18:23 u-boot.fex
-rw-rw-r-- 1 david david  244384 Sep 13 18:23 u-boot-spinor.fex
-rwxrwxr-x 1 david david  144896 Sep 13 18:23 usbtool.fex
-rwxrwxr-x 1 david david  128000 Sep 13 18:23 usbtool_test.fex

**Comment by BPI-SINOVOIP** [comment]
Hi @dtischler ,

It seems that files in out/tulip-m64 are incorrect, please check https://github.com/BPI-SINOVOIP/BPI-M64-bsp-4.4/tree/master/out/tulip-m64

**Comment by dtischler** [comment]
Thank you @BPI-SINOVOIP , I do see that those file are missing.  I am deleting and cloning the repository one more time to make sure everything gets downloaded properly.  However, don't those files get created dynamically, as part of the build process?  I am making changes to the kernel configuration, turning on a few additional items that I need compiled into the kernel.  Thus, since I am modifying the kernel configuration, don't those files need to be recreated and moved to the output directory as part of the build and pack process?

Thanks again!

**Comment by dtischler** [comment]
Aha, yes, I thought it needed to be dynamically built as part of the process, because the name of the folder is "out" as you mentioned.

The new download is running, it will done shortly then I can try again.   Thanks!

**Comment by dtischler** [comment]
@BPI-SINOVOIP - Excellent, this time it worked!  It seems that deleting my directory and re-downloading worked.  Thanks!  

Just flash the "tina_tulip-m64_uart0.img" file to the board using the Allwinner PhoenixSuite utility?

.........
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/qnx6/Kconfig
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/qnx6/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/sysfs/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/sysfs/Kconfig
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/sysfs/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/squashfs/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/squashfs/Kconfig
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/squashfs/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/Kconfig
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/jffs2/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/jffs2/Kconfig
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/jffs2/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/cramfs/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/cramfs/Kconfig
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/cramfs/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/cachefiles/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/cachefiles/Kconfig
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/cachefiles/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/jbd2/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/jbd2/Kconfig
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/jbd2/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/openpromfs/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/openpromfs/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/bfs/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/bfs/Kconfig
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/bfs/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/sysv/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/sysv/Kconfig
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/fs/sysv/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/bpf/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/bpf/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/kfifo/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/kfifo/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/hidraw/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/hidraw/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/seccomp/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/seccomp/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/trace_events/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/trace_events/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/kobject/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/kobject/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/configfs/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/configfs/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/rpmsg/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/rpmsg/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/mic/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/mic/mpssd/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/mic/mpssd/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/kdb/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/kdb/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/uhid/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/uhid/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/livepatch/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/livepatch/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/kprobes/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/kprobes/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/Kconfig
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/hw_breakpoint/
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/hw_breakpoint/Makefile
usr/src/linux-headers-4.4.89-BPI-M64-Kernel/samples/Makefile
usr/lib/u-boot/bananapi/
usr/lib/u-boot/bananapi/bpi-m64/
usr/lib/u-boot/bananapi/bpi-m64/BPI-M64-720P-linux4.4-8k.img.gz
usr/lib/u-boot/bananapi/bpi-m64/BPI-M64-LCD7-linux4.4-8k.img.gz
usr/lib/u-boot/bananapi/bpi-m64/BPI-R18-AVS-720P-linux4.4-8k.img.gz

 Build success!


david@david-VirtualBox:~/Desktop/BPI-M64-bsp-4.4$ ls -l out/tulip-m64/
total 63212
-rw-rw-r-- 1 david david 16777216 Sep 13 19:27 boot.img
drwxr-xr-x 3 root  root      4096 Sep 13 20:27 image
-rw-rw-r-- 1 david david 17301504 Sep 13 19:27 rootfs.img
-rwxr-xr-x 1 root  root  39058432 Sep 13 20:27 tina_tulip-m64_uart0.img
-rw-rw-r-- 1 david david  4206182 Sep 13 19:27 tulip-m64-uImage
david@david-VirtualBox:~/Desktop/BPI-M64-bsp-4.4$

**Comment by BPI-SINOVOIP** [comment]
Hi @dtischler ,

This repository is just for bsp build, and output binaries are all in SD folder. It can't be used to create a complete flashable linux image. You can download the bpi images from [wiki.banana-pi.org/Banana_Pi_BPI-M64](url) and try to familiar with the image partition structure. After that,  I think you can update your build objects to this image or you can create another Linux image by yourself.

About bpi image download and flash, please ref to [wiki.banana-pi.org/Getting_Started_with_M64](url)

Thanks,
DK

**Comment by dtischler** [comment]
Ah, thank you for this information.  I did not realize that these were not complete, flashable images.  I can use these pieces to place together an Ubuntu system though, thank you.
