### ISSUE TITLE
SPIDEV is not showed under /DEV

### ISSUE THREAD

**Issue by shaddow501** [BPI-SINOVOIP/BPI-M64-bsp-4.4#3]
Hello

How to get the SPI working? 
On the sys_config.fex it is enabled but still doesnt show in the /DEV

**Comment by BPI-SINOVOIP** [comment]
please refer to https://github.com/BPI-SINOVOIP/BPI-M64-bsp-4.4/commit/d505844b95497d2364f1d8f5b347ded29fb1da51
