### ISSUE TITLE
No support for simple & common HDMI 5" 800x480 LCD

### ISSUE THREAD

**Issue by shaddow501** [BPI-SINOVOIP/BPI-M64-bsp-4.4#4]
Hello

How to add the support for simple and common 5" HDMI 800x480 LCD?

[https://www.elecrow.com/wiki/index.php?title=HDMI_Interface_5_Inch_800x480_TFT_Display]

BananaPI  get their modules similar to RPI so why can they support the same accessories as RPI? it is a simple display!!

**Comment by BPI-SINOVOIP** [comment]
https://github.com/BPI-SINOVOIP/BPI-M64-bsp-4.4/commit/bfb24fcea06195ab9f74d037454a0b5ff1dcf74f

**Comment by shaddow501** [comment]
Hello, you added support for 1024x600 but not for 800x480...

**Comment by BPI-SINOVOIP** [comment]
I mean, refer to that commit and modify the code to support your special panel

**Comment by shaddow501** [comment]
How to set the correct parameters in this file ?
linux-sunxi/drivers/video/fbdev/sunxi/disp2/hdmi/hdmi_core.c

**Comment by shaddow501** [comment]
Since 800x480 displays are very common why cant you add it as well ?
